# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    container_name: todo_app
    restart: unless-stopped
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL='postgresql+psycopg2://todod3v:fastD0ck@db:5432/todo'
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    container_name: todo_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=todod3v
      - POSTGRES_PASSWORD=fastD0ck
      - POSTGRES_DB=todo

volumes:
  postgres_data: